version: "1.1"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: container_backend
    ports:
      - "8080:8080"
    networks:
      - net

  frontend:
    image: nginx
    container_name: container_frontend
    ports:
      - "8000:8000"
    volumes:
      - "./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./frontend/nginx/html:/usr/share/nginx/html"
    depends_on:
      - backend
    networks:
      - net
